imx: cpufreq: fix build error using poky tool chain
Fix below build error on i.MX8QXP when using poky
tool chain:

CC	plat/imx/common/cpufreq.c
plat/imx/common/cpufreq.c:27:18:
error: "ap_cluster_index" defined but not used
[-Werror=unused-const-variable=]

Signed-off-by: Anson Huang <Anson.Huang@nxp.com>