fix(scmi-msg): base: fix build break
fix below build error due to strict type checking

include/lib/utils_def.h:70:20: error: comparison of distinct pointer types lacks a cast [-Werror]
   70 |         (void)(&_x == &_y);             \
      |                    ^~
drivers/scmi-msg/base.c:154:25: note: in expansion of macro ‘MIN’
  154 |                 count = MIN(count - a2p->skip, msg->out_size - sizeof(p2a));
      |                         ^~~

Signed-off-by: Jacky Bai <ping.bai@nxp.com>
Change-Id: I61ace5c1d295d708195693523dc3dbabccef48c5