MLK-22488 imx8qm: Remove SC_R_GIC_SMMU from non-secure access list
SC_R_GIC_SMMU is a master resource, we can't set peripheral
permission to this resource, otherwise the API will return below error
on latest SCFW, because SCFW has added a resource type check.
On old SCFW, the API does nothing to a master resource. So remove the
resource from ns_access_allowed array.

ERROR: sc_rm_set_peripheral_permissions: rsrc 14, ret 3

Signed-off-by: Ye Li <ye.li@nxp.com>